# Generated by Django 6.1.1 on 2026-09-18 08:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre_foncier', models.CharField(max_length=100, unique=True)),
                ('propriete_dite', models.CharField(max_length=300)),
                ('lot_number', models.CharField(blank=True, max_length=50)),
                ('affaire_ref', models.CharField(blank=True, max_length=300)),
                ('geometre', models.CharField(blank=True, max_length=200)),
                ('date_leve', models.DateField(blank=True, null=True)),
                ('service_cadastre', models.CharField(blank=True, max_length=200)),
                ('surface_document_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('surface_calculee_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('correction_lambert_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_pdf_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_cadastraux', to='projets.projet')),
            ],
            options={
                'db_table': 'cadastre_lots',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DistanceCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_label', models.CharField(max_length=100)),
                ('croquis_m', models.DecimalField(decimal_places=3, max_digits=10)),
                ('calcule_m', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ecart_m', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_checks', to='cadastre.lot')),
            ],
            options={
                'db_table': 'cadastre_distance_checks',
                'indexes': [models.Index(fields=['lot'], name='cadastre_di_lot_id_72987c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Borne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sequence', models.IntegerField()),
                ('x_lambert', models.DecimalField(decimal_places=3, max_digits=12)),
                ('y_lambert', models.DecimalField(decimal_places=3, max_digits=12)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bornes', to='cadastre.lot')),
            ],
            options={
                'db_table': 'cadastre_bornes',
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['lot'], name='cadastre_bo_lot_id_7bdf0a_idx')],
                'constraints': [models.UniqueConstraint(fields=('lot', 'sequence'), name='unique_borne_sequence_per_lot')],
            },
        ),
        migrations.CreateModel(
            name='ReferencePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('distance_m', models.DecimalField(decimal_places=3, max_digits=10)),
                ('bearing_deg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_points', to='cadastre.lot')),
            ],
            options={
                'db_table': 'cadastre_reference_points',
                'indexes': [models.Index(fields=['lot'], name='cadastre_re_lot_id_9e8c28_idx')],
            },
        ),
    ]
