# Generated by Django 6.1.1 on 2026-09-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0007_lot_decalage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='annotations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
