# Generated by Django 6.1.1 on 2026-09-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0004_lot_prestation_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='zone',
            field=models.CharField(choices=[('nord', 'Nord'), ('sud', 'Sud')], default='nord', max_length=4),
        ),
    ]
