# Generated by Django 6.1.1 on 2026-09-25 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0005_lot_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='ajustements_m2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='Ajustement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('appoint', 'Appoint'), ('deduction', 'Déduction')], default='deduction', max_length=10)),
                ('m2', models.DecimalField(decimal_places=4, max_digits=14)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustements', to='cadastre.lot')),
            ],
            options={
                'db_table': 'cadastre_ajustements',
                'ordering': ['id'],
            },
        ),
    ]
