# Generated by Django 6.1.1 on 2026-09-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0006_ajustements'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='decalage_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lot',
            name='decalage_y',
            field=models.FloatField(default=0),
        ),
    ]
