# Generated by Django 6.1.1 on 2026-09-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0008_lot_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='pivot_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lot',
            name='pivot_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lot',
            name='rotation_deg',
            field=models.FloatField(default=0),
        ),
    ]
