"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')
# Online mode: CARTE_ENV_FILE points at a file holding DATABASE_URL (a shared hosted Postgres).
if os.getenv('CARTE_ENV_FILE'):
    load_dotenv(os.getenv('CARTE_ENV_FILE'), override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-c*pex&1)p(=$_jhzbauus7m0to1&a@3l#6ots&8s^zul8ccrbq',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h for h in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'core',
    'employees',
    'clients',
    'resources',
    'projets',
    'cadastre',
    'consultation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    origin
    for origin in os.getenv('DJANGO_CORS_ALLOWED_ORIGINS', 'http://localhost:5174,http://127.0.0.1:5174').split(',')
    if origin
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# CARTE_DB=sqlite runs on a single local file (the standalone .exe); anything else uses Postgres/PostGIS.
CARTE_DB = os.getenv('CARTE_DB', 'postgres')
DATA_DIR = Path(os.getenv('CARTE_DATA_DIR', BASE_DIR))

DATABASE_URL = os.getenv('DATABASE_URL', '')

if DATABASE_URL:
    # Online mode: one shared hosted Postgres (e.g. Neon). Uploaded files live in the database too.
    from urllib.parse import parse_qs, unquote, urlparse

    _u = urlparse(DATABASE_URL)
    _q = {k: v[0] for k, v in parse_qs(_u.query).items()}
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _u.path.lstrip('/'),
            'USER': unquote(_u.username or ''),
            'PASSWORD': unquote(_u.password or ''),
            'HOST': _u.hostname,
            'PORT': _u.port or 5432,
            'CONN_MAX_AGE': 0,
            'DISABLE_SERVER_SIDE_CURSORS': True,  # behind a transaction pooler
            'OPTIONS': {'sslmode': _q.get('sslmode', 'require'), 'prepare_threshold': None},
        }
    }
elif CARTE_DB == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': DATA_DIR / 'carte.sqlite3',
            'OPTIONS': {'timeout': 30},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'carte_extract'),
            'USER': os.getenv('POSTGRES_USER', 'glbops'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'glbops'),
            'HOST': os.getenv('POSTGRES_HOST', '127.0.0.1'),
            'PORT': os.getenv('POSTGRES_PORT', '5435'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Standalone app: Django itself serves the built frontend (frontend/dist) and the uploaded files.
SERVE_FRONTEND = os.getenv('CARTE_SERVE_FRONTEND', '') == '1'
FRONTEND_DIST = Path(os.getenv('CARTE_FRONTEND_DIST', BASE_DIR.parent / 'frontend' / 'dist'))


# Media (uploaded attachments)
if DATABASE_URL or os.getenv('CARTE_FILES') == 'db':
    STORAGES = {
        'default': {'BACKEND': 'core.storage.DatabaseStorage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    }

MEDIA_URL = '/media/'
MEDIA_ROOT = DATA_DIR / 'media'


# OCR microservice (backend/ocr-service) — see core/ocr.py

OCR_SERVICE_URL = os.getenv('OCR_SERVICE_URL', 'http://127.0.0.1:8501')


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
