# Generated by Django 6.1.1 on 2026-09-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_attachments_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='reprog_date',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='prestation',
            name='reprog_en_attente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestation',
            name='reprog_motif',
            field=models.TextField(blank=True),
        ),
    ]
