# Generated by Django 6.1.1 on 2026-09-21 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_vehicule_papiers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sortie', 'Sortie'), ('retour', 'Retour')], max_length=10)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('par_nom', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('kilometrage', models.PositiveIntegerField(blank=True, null=True)),
                ('par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='resources.resource')),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
    ]
