# Generated by Django 6.1.1 on 2026-09-17 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nature_demandee', models.CharField(blank=True, max_length=300)),
                ('nature_executee', models.CharField(blank=True, max_length=300)),
                ('date_debut_demande', models.DateField(blank=True, null=True)),
                ('date_fin_demande', models.DateField(blank=True, null=True)),
                ('date_debut_exec', models.CharField(blank=True, max_length=30)),
                ('date_fin_exec', models.CharField(blank=True, max_length=30)),
                ('chemin_bureau', models.CharField(blank=True, max_length=500)),
                ('date_debut_bureau', models.DateField(blank=True, null=True)),
                ('date_fin_bureau', models.DateField(blank=True, null=True)),
                ('date_debut_controle', models.DateField(blank=True, null=True)),
                ('date_fin_controle', models.DateField(blank=True, null=True)),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('ref', models.CharField(blank=True, max_length=50)),
                ('chemin', models.CharField(blank=True, max_length=500)),
                ('cd_n', models.CharField(blank=True, max_length=50)),
                ('disque_n', models.CharField(blank=True, max_length=50)),
                ('stage', models.CharField(choices=[('demande', 'Demande'), ('prestation', 'Prestation demandée'), ('affectation', 'Affectation terrain'), ('execution', 'Exécution'), ('bureau', 'Traitement bureau'), ('controle', 'Contrôle'), ('livraison', 'Livraison')], default='demande', max_length=20)),
                ('cycles', models.PositiveIntegerField(default=0)),
                ('reprogramme', models.BooleanField(default=False)),
                ('non_conformite_source', models.CharField(blank=True, choices=[('chantier', 'Agent Chantier (exécution terrain)'), ('bureau', 'Agent Bureau (traitement)')], max_length=20)),
                ('agent_bureau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestations_bureau', to='employees.employee')),
                ('agent_chantier', models.ManyToManyField(blank=True, related_name='prestations_chantier', to='employees.employee')),
                ('agent_controle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestations_controle', to='employees.employee')),
                ('materiels', models.ManyToManyField(blank=True, related_name='prestations', to='resources.resource')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestations_vehicule', to='resources.resource')),
            ],
            options={
                'ordering': ['-date_debut_demande'],
            },
        ),
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='projets.prestation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('reference_fonciere', models.CharField(blank=True, max_length=100)),
                ('situation', models.CharField(blank=True, max_length=300)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('nature_prestation_projet', models.CharField(blank=True, max_length=200)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='clients.client')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='prestation',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='projets.projet'),
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('agents', models.ManyToManyField(blank=True, related_name='taches', to='employees.employee')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='projets.prestation')),
            ],
        ),
    ]
