# Generated by Django 6.1.1 on 2026-09-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='boundary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
