# Generated by Django 6.1.1 on 2026-09-17 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Dispatcher', 'Dispatcher'), ('Directrice', 'Directrice'), ('Agent Chantier', 'Agent Chantier'), ('Agent Bureau', 'Agent Bureau'), ('Agent Contrôle', 'Agent Contrôle')], max_length=30)),
                ('poste', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Congé payé', 'Congé payé'), ('Congé maladie', 'Congé maladie'), ('Congé sans solde', 'Congé sans solde'), ('Autre', 'Autre')], max_length=30)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='employees.employee')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
