# Generated by Django 6.1.1 on 2026-09-23 15:12

from django.db import migrations, models

from core.mentions import find_mentioned


def backfill_mentions(apps, schema_editor):
    """Comments written before mentions were stored: resolve them from their text once."""
    Comment = apps.get_model("core", "Comment")
    Employee = apps.get_model("employees", "Employee")
    employees = list(Employee.objects.all())
    for comment in Comment.objects.filter(text__contains="@"):
        comment.mentions.set(find_mentioned(comment.text, employees))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment_read_by'),
        ('employees', '0002_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in', to='employees.employee'),
        ),
        migrations.RunPython(backfill_mentions, migrations.RunPython.noop),
    ]
