# Generated by Django 6.1.1 on 2026-09-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attachment_ocr_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='chemin',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, upload_to='attachments/%Y/%m/'),
        ),
    ]
