# Generated by Django 6.1.1 on 2026-09-17 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('station_totale', 'Station totale'), ('gps', 'GPS / GNSS'), ('drone', 'Drone'), ('scanner', 'Scanner 3D / LiDAR'), ('niveau', 'Niveau optique'), ('vehicule', 'Véhicule'), ('autre', 'Autre')], max_length=30)),
                ('marque', models.CharField(blank=True, max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('operationnel', 'Opérationnel'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service')], default='operationnel', max_length=20)),
                ('derniere_calibration', models.DateField(blank=True, null=True)),
                ('prochaine_calibration', models.DateField(blank=True, null=True)),
                ('emplacement', models.CharField(blank=True, max_length=200)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('valeur', models.CharField(blank=True, max_length=50)),
                ('fournisseur', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(max_length=300)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_log', to='resources.resource')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
