# Generated by Django 6.1.1 on 2026-09-20 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_user'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='assurance_compagnie',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='resource',
            name='assurance_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='assurance_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='assurance_police',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='assurance_prime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='carburant',
            field=models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('essence', 'Essence'), ('hybride', 'Hybride'), ('electrique', 'Électrique')], max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='carte_carburant',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='resource',
            name='conducteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules_habituels', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='resource',
            name='entretien_prochain_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='entretien_prochain_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='kilometrage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='kilometrage_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='vignette_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='vignette_paiement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='visite_technique_derniere',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='visite_technique_prochaine',
            field=models.DateField(blank=True, null=True),
        ),
    ]
